### ISSUE TITLE
Erro no módulo ej-conversations e pushtogether-math

### ISSUE THREAD

**Issue by arkye** [ejplatform/ej-server#56]
Refatorações no Docker busca otimizar o _pipeline_ e a corretude do ambiente do sistema. Após substituir o comando `pip` para `pip3`, todos os módulos definidos em todos os requirements (base, test e production) funcionaram, exceto `ej-conversations` e `pushtogether-math`.

Tentativas para descobrir a origem do erro foram feitas mas sem sucesso.

## `ej-conversations`

```
Collecting git+https://github.com/ejplatform/ej-conversations.git@develop (from -r /app/requirements/base.txt (line 72))
  Cloning https://github.com/ejplatform/ej-conversations.git (to revision develop) to /tmp/pip-req-build-htn7f5cn
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-htn7f5cn/setup.py", line 9, in <module>
        packages=find_packages('src'),
      File "/usr/lib/python3.5/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 352, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/usr/lib/python3.5/distutils/dist.py", line 395, in parse_config_files
        parser.read(filename)
      File "/usr/lib/python3.5/configparser.py", line 696, in read
        self._read(fp, filename)
      File "/usr/lib/python3.5/configparser.py", line 1012, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 164: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-htn7f5cn/
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip3 install -r /app/requirements/base.txt' returned a non-zero code: 1
```

## `pushtogether-math`

```
Collecting pushtogether-math (from -r /app/requirements/base.txt (line 70))
  Downloading https://files.pythonhosted.org/packages/3e/37/bb58d7dc6049480d0d2cb9404a63431193715ae8d39d902b040daeed2c1c/pushtogether-math-0.1.50.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8sfsz69y/pushtogether-math/setup.py", line 9, in <module>
        packages=find_packages('src'),
      File "/usr/lib/python3.5/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 352, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/usr/lib/python3.5/distutils/dist.py", line 395, in parse_config_files
        parser.read(filename)
      File "/usr/lib/python3.5/configparser.py", line 696, in read
        self._read(fp, filename)
      File "/usr/lib/python3.5/configparser.py", line 1012, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 166: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8sfsz69y/pushtogether-math/
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip3 install -r /app/requirements/base.txt' returned a non-zero code: 1
```

**Comment by fabiommendes** [comment]
Johnatan. o docker do debian possui um bug (feature?) que não configura o locale e isso quebra alguns pacotes Python. O problema geralmente aparece na instalação quando temos um pacote Python3 c/ autores ou descrição que contenham acentos (mas mesmo se passar, vai dar pau na primeira string com acento que aparecer em produção). Se configurar o locale, o problema desaparece.

**Comment by luanguimaraesla** [comment]
Descobrimos isso ontem à tarde. Já está resolvido :D
